PythonWebDevelopment/Exams/petstagram/accounts/urls.py
from django.urls import path

from accounts.views import register, login_user, logout_user, profile_details

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile_details, name='profile_details'),
]

PythonWebDevelopment/Exams/petstagram/pets/urls.py
from django.urls import path

from pets.views import get_all, pet_details, like_pet, create, edit, delete, comment_pet

urlpatterns = [
    path('', get_all, name='pets_list'),
    path('details/<int:pet_id>/', pet_details, name='pet_details'),
    path('like/<int:pet_id>/', like_pet, name='like_pet'),
    path('create/', create, name='create'),
    path('edit/<int:pet_id>', edit, name='edit'),
    path('delete/<int:pet_id>', delete, name='delete'),
    path('comment/<int:pet_id>', comment_pet, name='comment_pet'),
]

PythonWebDevelopment/Exams/petstagram/petstagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from petstagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('common.urls', 'common'), namespace="common")),
    path('pets/', include(('pets.urls', 'pets'), namespace="pets")),
    path('account/', include(('accounts.urls', 'accounts'), namespace="account")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PythonWebDevelopment/Exams/petstagram/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models

from accounts.manager import PetstagramUserManager


class PetstagramUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'

    objects = PetstagramUserManager()


class Profile(models.Model):
    profile_image = models.ImageField(upload_to='images/profiles', blank=True)
    user = models.OneToOneField(PetstagramUser, on_delete=models.CASCADE, primary_key=True)


from .signals import *

PythonWebDevelopment/Exams/petstagram/accounts/forms.py
from django.contrib.auth import get_user_model, authenticate
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from accounts.models import Profile

UserModel = get_user_model()


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Profile
        exclude = ('user',)


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = UserModel
        fields = ("email",)


class SignInForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    user = None
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput(),)

    def clean_password(self):
        self.user = authenticate(
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password'],
        )

        if not self.user:
            raise ValidationError('Email and/or password incorrect')

    def save(self):
        return self.user

PythonWebDevelopment/Exams/petstagram/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from accounts.forms import SignUpForm, SignInForm, ProfileForm
from accounts.models import Profile
from pets.models import Pet


def register(request):
    if request.POST:
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('common:landing_page')

    else:
        form = SignUpForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/register.html', context)


def login_user(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('common:landing_page')
    form = SignInForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout_user(request):
    logout(request)
    return redirect('common:landing_page')


@login_required(login_url='accounts:login')
def profile_details(request):
    profile = Profile.objects.get(pk=request.user.id)
    user_pets = Pet.objects.filter(user_id=request.user.id)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('common:landing_page')
    else:
        form = ProfileForm(instance=profile)

    context = {
        'form': form,
        'profile': profile,
        'pets': user_pets,
    }

    return render(request, 'accounts/user_profile.html', context)

PythonWebDevelopment/Exams/petstagram/templates/accounts/login.html
{% extends 'pets/main.html' %}
{% block site_content %}
<div class="container">
    <form class="w-50 m-auto" method="post" style="border: 1px solid grey; margin: 10% 0; padding: 5% 5%" action="{% url 'accounts:login' %}">
      <h2>Login</h2>
      {% csrf_token %}
        {{ form }}
        <p></p>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

PythonWebDevelopment/Exams/petstagram/templates/accounts/register.html
{% extends "pets/main.html" %}
{% block site_content %}
<div class="container-fluid" style="background-image: none">
    <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
          <form style="border: 1px solid grey; margin: 10% 0; padding: 10% 5%" method="post" action="{% url 'accounts:register' %}">
            <h2>Sign up</h2>
            {% csrf_token %}
              {{ form }}
            <button class="btn btn-primary" type="submit">Sign up</button>
            <span>Have an account?<a href="{% url 'accounts:register' %}" style="color:orange">Sign in here</a></span>
          </form>
    </div>
    <div class="col-lg-3"></div>
        </div>
</div>
{% endblock %}

PythonWebDevelopment/Exams/petstagram/templates/accounts/user_profile.html
{% extends 'pets/main.html' %}
{% load static %}
{% block site_content %}
    <div class="text-center">
        <h1>Hello, {{ profile.user }}!</h1>
        <h5>This is your profile</h5>
        {% if profile.profile_image %}
            <img class="rounded-circle mb-3" src="{{ profile.profile_image.url }}" alt="" width="140" height="140">
        {% else %}
            <img class="rounded-circle mb-3" src="{% static 'images/profile.jpeg' %}" alt="" width="140" height="140">
        {% endif %}
        <div class="w-50 m-auto">
            <form method="post" action="{% url 'accounts:profile_details' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-2">Update</button>
            </form>
        </div>
    </div>
    <hr>
    {% if pets %}
        <h2 class='text-center'>These are you pet photos</h2>
        <div class="row">
            <div class="row">
                {% for pet in pets %}
                    <div class="col-lg-4">
                        <div class="card" style="width: 18rem;">
                            <img src="{{ pet.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                                <p class="card-text">{{ pet.description }}</p>
                                <p class="card-text"><strong>Owner: {{ pet.user }}</strong></p>
                                <a href="{% url 'pets:pet_details' pet.id %}" class="btn btn-primary">See details</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="text-center">
            <h2>You have no pets</h2>
            <a href="{% url 'pets:create' %}" class="btn btn-success">Add Pet Photo</a>
        </div>
    {% endif %}
{% endblock %}