PythonWebDevelopment/Exams/petstagram/pets/urls.py
from django.urls import path

from pets.views import get_all, pet_details, like_pet, create, edit, delete, comment_pet

urlpatterns = [
    path('', get_all, name='pets_list'),
    path('details/<int:pet_id>/', pet_details, name='pet_details'),
    path('like/<int:pet_id>/', like_pet, name='like_pet'),
    path('create/', create, name='create'),
    path('edit/<int:pet_id>', edit, name='edit'),
    path('delete/<int:pet_id>', delete, name='delete'),
    path('comment/<int:pet_id>', comment_pet, name='comment_pet'),
]

PythonWebDevelopment/Exams/petstagram/petstagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from petstagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('common.urls', 'common'), namespace="common")),
    path('pets/', include(('pets.urls', 'pets'), namespace="pets")),
    path('account/', include(('accounts.urls', 'accounts'), namespace="account")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PythonWebDevelopment/Exams/petstagram/templates/landing_page.html
{% extends 'pets/main.html' %}
{% block site_content %}
    <div class="container">
        <div class="jumbotron parent">
            <img style="width: 100%"
                 src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
            <div class="absolute">
                <h1 class="display-4">Welcome to Petstagram</h1>
                <p class="lead">Share your pets photos.</p>
                <hr class="my-4">
                <div class="inner cover">
                    <h1 class="cover-heading"></h1>
                    <div class="row">
                        {% if not user.is_authenticated %}
                            <div class="col-lg-6">
                                <p class="lead">Already have an account?
                                    <br>
                                    <a href="{% url 'accounts:login' %}" class="btn btn-lg btn-secondary">sign in</a>
                                </p>
                            </div>
                            <div class="col-lg-6">
                                <p class="lead"> Do not have an account? <br>
                                    <a href="{% url 'accounts:register' %}" class="btn btn-lg btn-secondary">sign up</a>
                                </p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PythonWebDevelopment/Exams/petstagram/templates/pet_create.html
{% extends 'pets/main.html' %}
{% block site_content %}
    <div class="container">
        <h1 class="text-center">Add new pet photo</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" class="furniture-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <button class="btn btn-primary mt-2" type="submit">Create</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
{% endblock %}

PythonWebDevelopment/Exams/petstagram/templates/pet_delete.html
{% extends 'pets/main.html' %}
{% block site_content %}
    <div class="container">
        <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete pet_name?</h1>
            <div class="m-auto d-flex justify-content-center">
                     <div class="m-2">
                         <form method="post">
                            {% csrf_token %}
                                <input type="submit" value="Confirm" class="btn btn-danger" />
                         </form>
                    </div>
                    <div class="m-2">
                        <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                    </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

PythonWebDevelopment/Exams/petstagram/templates/pet_details.html
{% extends 'pets/main.html' %}
{% block site_content %}
    <div class="container">
        <div class="d-flex">
            <div class="d-inline p-2 w-50">
                <img src="{{ pet.image.url }}" class="w-50 rounded mx-auto d-block" alt="{{ pet.description }}">
            </div>
            <div class="d-inline p-2 w-50">
                <div class="d-flex justify-content-between">
                    <h5><u>Type:</u> {{ pet.type }}</h5>
                    <h5><u>Name:</u> {{ pet.name }}</h5>
                    <h5><u>Age:</u> {{ pet.age }}</h5>
                    <h5><u>Owner:</u> {{ pet.user }}</h5>
                </div>
                <p class="mt-2">Description: {{ pet.description }}</p>
                {% if is_owner %}
                    <div>
                        <a href="{% url 'pets:edit' pet.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'pets:delete' pet.id %}" class="btn btn-danger">Delete</a>
                        <p class="mt-2">Likes: {{ pet.likes_count }}</p>
                    </div>
                {% else %}
                    <a href="{% url 'pets:like_pet' pet.id %}">
                        {% if is_liked %}
                            <i class="fa fa-heart" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                        {% endif %}
                    </a>
                    <p class="mt-2">Likes: {{ pet.likes_count }}</p>
                {% endif %}
            </div>
        </div>
        <div class="d-block" style="background-color: #f1e3e3; padding:2%">
            {% if comments %}
                {% for comment in comments %}
                    <div class="box">
                        <h5><u>{{ comment.user }}</u>: <em>{{ comment.comment }}</em></h5>
                        <hr>
                    </div>
                {% endfor %}
            {% else %}
                <div class="box">
                    <h3>There are no comments for this pet. </h3>
                </div>
            {% endif %}
            {% if not is_owner %}
                <div class="box">
                    <form method="post" action="{% url 'pets:comment_pet' pet.id %}">
                        {% csrf_token %}
                        {{ comment_form }}
                        <button class="btn btn-primary mt-2" type="submit">Add comment</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

PythonWebDevelopment/Exams/petstagram/templates/pet_edit.html
{% extends 'pets/main.html' %}
{% block site_content %}
    <div class="container">
        <h1 class="text-center">Edit pet photo</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" class="furniture-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <button class="btn btn-primary mt-2" type="submit">Edit</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
{% endblock %}

PythonWebDevelopment/Exams/petstagram/templates/pets_list.html
{% extends 'pets/main.html' %}
{% block site_content %}
    <div class="container">
        <h1 class='text-center'>All pet photos</h1>
        <div class="row">
            {% for pet in pets %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ pet.image.url }}" class="card-img-top" alt="{{ pet.description }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ pet }}</h5>
                        <p class="card-text">{{ pet.description }}</p>
                        <a href="{% url 'pets:pet_details' pet.id %}" class="btn btn-primary">See details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}