PythonWebDevelopment/Exams/petstagram/common/urls.py
from django.urls import path

from common.views import landing_page

urlpatterns = [
    path('', landing_page, name='landing_page')
]

PythonWebDevelopment/Exams/petstagram/pets/urls.py
from django.urls import path

from pets.views import get_all, pet_details, like_pet, create, edit, delete, comment_pet

urlpatterns = [
    path('', get_all, name='pets_list'),
    path('details/<int:pet_id>/', pet_details, name='pet_details'),
    path('like/<int:pet_id>/', like_pet, name='like_pet'),
    path('create/', create, name='create'),
    path('edit/<int:pet_id>', edit, name='edit'),
    path('delete/<int:pet_id>', delete, name='delete'),
    path('comment/<int:pet_id>', comment_pet, name='comment_pet'),
]

PythonWebDevelopment/Exams/petstagram/petstagram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from petstagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('common.urls', 'common'), namespace="common")),
    path('pets/', include(('pets.urls', 'pets'), namespace="pets")),
    path('account/', include(('accounts.urls', 'accounts'), namespace="account")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PythonWebDevelopment/Exams/petstagram/pets/models.py
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class Pet(models.Model):
    def __str__(self):
        return f'{self.name}, {self.age}, {self.type}'

    DOG = 'dog'
    CAT = 'cat'
    PARROT = 'parrot'
    PET_TYPE = (
        (DOG, "Dog"),
        (CAT, 'Cat'),
        (PARROT, 'Parrot')
    )

    type = models.CharField(max_length=6, choices=PET_TYPE)
    name = models.CharField(max_length=6)
    age = models.PositiveIntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='images/pets')
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)


from .signals import *

PythonWebDevelopment/Exams/petstagram/pets/forms.py
import os
from os.path import join

from django import forms

from pets.models import Pet
from petstagram import settings


class PetCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Pet
        exclude = ('user', )


class EditPetForm(PetCreateForm):
    def save(self, commit=True):
        db_pet = Pet.objects.get(pk=self.instance.id)
        if commit:
            image_path = join(settings.MEDIA_ROOT, str(db_pet.image))
            os.remove(image_path)
            return super().save(commit)

PythonWebDevelopment/Exams/petstagram/pets/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from common.forms import CommentForm
from core.decorators import can_like, can_delete_or_edit
from pets.forms import PetCreateForm, EditPetForm
from pets.models import Pet, Like


def get_all(request):
    context = {
        'pets': Pet.objects.all(),
    }
    return render(request, "pets_list.html", context)


@login_required(login_url='accounts:login')
def pet_details(request, pet_id):
    current_pet = Pet.objects.get(pk=pet_id)
    current_pet.likes_count = current_pet.like_set.count()
    is_owner = current_pet.user == request.user
    is_liked_by_user = current_pet.like_set.filter(user_id=request.user.id).exists()

    context = {
        'pet': current_pet,
        'is_owner': is_owner,
        'is_liked': is_liked_by_user,
        'comment_form': CommentForm(
            initial={
                'pet_id': pet_id,
            }),
        'comments': current_pet.comment_set.all(),
    }

    return render(request, 'pet_details.html', context)


@can_like(Pet)
def like_pet(request, pet_id):
    current_pet = Pet.objects.get(pk=pet_id)
    is_liked_by_user = current_pet.like_set.filter(user_id=request.user.id).first()

    if is_liked_by_user:
        is_liked_by_user.delete()
    else:
        like = Like(pet=current_pet, user=request.user)
        like.save()

    return redirect('pets:pet_details', pet_id)


@login_required(login_url='accounts:login')
def create(request):
    pet = Pet()
    return persist(request, pet, "pet_create.html")


@can_delete_or_edit(Pet)
def edit(request, pet_id):
    pet = Pet.objects.get(pk=pet_id)
    EditPetForm(request.POST, request.FILES, instance=pet)
    return persist(request, pet, "pet_edit.html")


@can_delete_or_edit(Pet)
def delete(request, pet_id):
    pet = Pet.objects.get(pk=pet_id)
    if request.method == "GET":
        return render(request, "pet_delete.html", {'pet': pet})
    else:
        pet.delete()
        return redirect("pets:pets_list")


@login_required(login_url='accounts:login')
def comment_pet(request, pet_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.save()

    return redirect("pets:pet_details", pet_id)


def persist(request, pet, template, form=None):
    if request.method == "GET":
        form = PetCreateForm(instance=pet)
        return render(request, template, {'form': form})
    else:
        if not form:
            form = PetCreateForm(request.POST, request.FILES, instance=pet)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.user = request.user
            pet.save()

            return redirect('pets:pet_details', pet.id)

        return render(request, template, {'form': form})

PythonWebDevelopment/Exams/petstagram/templates/pets/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <a class="nav-link" href="{% url 'common:landing_page' %}">Home</a>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pets:pets_list' %}">All Pet Photos</a>
            </li>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pets:create' %}">Add Pet Photo</a>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'accounts:profile_details' %}">Hello, {{ request.user }}!</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Sign Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block site_content %}
    {% endblock %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>
</html>